[project]
name = "ailearnssnake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pygame>=2.6.1",
    "torch>=2.8.0",
]
